spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/v1/user/**
          filters:
            - name: AuthenticationFilter


        - id: mistake-service
          uri: lb://mistake-service
          predicates:
            - Path=/v1/mistake/**
          filters:
            - name: AuthenticationFilter


        - id: mistake-listing-service
          uri: lb://mistake-listing-service
          predicates:
               - Path=/v1/mistake-listing/**
          filters:
            - name: AuthenticationFilter

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/v1/auth/**


      discovery:
        locator:
          enabled: true
    compatibility-verifier:
      enabled: false

server:
  port: 8889
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true



management:
  endpoints:
    web:
      exposure:
        include: "*"



