spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/v1/user/**

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/v1/security/**



      discovery:
        locator:
          enabled: true
    compatibility-verifier:
      enabled: false

server:
  port: 8889
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true



management:
  endpoints:
    web:
      exposure:
        include: "*"



